export const tokenSchema = {
    address: null,
	network: null,
	dex: [],
	name: null,
	symbol: null,
	price_usd: null,
	market_cap: null,
	ath: null,
	volume: null,
	supply: null,
	price_change_percentage_1h: null,
	price_change_percentage_24h: null,
	price_change_percentage_7d: null,
	price_change_percentage_14d: null,
	price_change_percentage_30d: null,
	price_change_percentage_200d: null,
	price_change_percentage_1y: null,
	sparkline: null
};